### ISSUE TITLE
[RFC]: Drop support for default serialization and static serializer factory

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-serializer#24]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 4.0.0  |
| BC Break?           | Yes |

### Goal

Remove support for `Serializer#setDefaultAdapter`, `Serializer#getDefaultAdapter`, `Serializer#serialize` and `Serializer#unserialize` which are static methods meant to be modified at runtime and used in a global scope.

### Background

Having these kinds of methods around provides "easy access" to *whatever* serializer to actually convert non-string values into strings. Since there is usually a bi-directional handling of serialized data, one should explicitly set the serializer anyway.

So instead of using `Serializer#unserialize` or `Serializer#serialize`, one should directly instantiate the adapter to not depend on magic stuff such as `Serializer#getDefaultAdapter`.

### Considerations

In case projects are actually using `Serializer#unserialize` and `Serializer#serialize`, they should instead convert that code:

```php
/** Before */
Serializer::setDefaultAdapter(IgBinary::class);
$serialized = Serializer::serializer(new stdClass);

/** After */
$serializer = new IgBinary();
$serialized = $serializer->serialize(new stdClass);
```

There should be no reason to rely on "whatever" serialization functionality as implicit code might lead to unwanted behavior.

### Proposal(s)

I'd just drop the whole `Serializer` class as it is meant to be used as a globally available function. Mostly the same was available in `laminas-cache` as a `StorageFactory` which was dropped in v3 and provided via `https://github.com/laminas/laminas-cache-storage-deprecated-factory` as a temporary solution for components which still rely on that kind of factory (such as [laminas-i18n](https://github.com/laminas/laminas-i18n/blob/646226a65eee614105cdaaeb1a639397ecaa3ad4/src/Translator/Translator.php#L223-L229))

I am unsure if this kind of factory is used in other components as of now but even tho, these components should find a way to create a serializer without using static factories but by using the appropriate plugin manager.

**Comment by boesing** [comment]
Might be helpful to have a service specified for the `SerializerInterface` so that one can fetch the "default" serializer from the container. This would enable projects to still have some "generic" way of serializing stuff without actually having to use static methods.

Having a dedicated factory around to help upstream projects to overwrite the default adapter might be useful.

```

final class SerializerFactory
{
     /** @param class-string<SerializerInterface> */
     public function __construct(private readonly string $serializerName)
     {}

     public function __invoke(ContainerInterface $container): SerializerInterface
     {
               $plugins = $container->get(AdapterPluginManager::class);
               return $plugins->get($serializerName);
     }
}
```

So we could already register this factory for the `PhpSerialize` serializer and it can be overridden by upstream projects.
Projects which use `Serializer::serialize` with passing an adapter - well, these can be refactored to directly call the method on the adapter itself and those passing alias/class-string of an adapter along with options are already aware of what serializer they want to use. Refactoring that code to instantiate these adapters on their own should be possible without big pain but reduces the amount of magic in laminas components.

**Comment by gsteel** [comment]
Not sure why `Serializer` is not just an interface and all the various implementations could have their own factory _(if required)_. `ConfigProvider` then lists all the implementations in `'factories'` and there's a default `'aliases'` for `SerializerInterface::class => PhpSerializer::class` - Then there's no need for a plugin manager. I know that would be a much bigger BC break, but fetching an implementation, or whatever the default is for the project, from the container would be easier to reason about no?

**Comment by boesing** [comment]
Yah, that is what I wanted to achieve with this comment:

> Might be helpful to have a service specified for the SerializerInterface so that one can fetch the "default" serializer from the container. This would enable projects to still have some "generic" way of serializing stuff without actually having to use static methods.

So projects can actually do `$container->get(SerializerInterface::class)` to retrieve a default Serializer from the container.
