### ISSUE TITLE
Factory is concrete instance instead of class string

### ISSUE THREAD

**Issue by kynx** [laminas/laminas-serializer#45]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.16.0

#### Summary

This isn't a bug per-se, but I'm wondering if best practice is being followed.

After an update to 2.16.0 one of my dependency smoke tests started failing. This was caused by https://github.com/laminas/laminas-serializer/pull/39/files#diff-f0a2f25e61573ecaca3a489ef6fca6a6106b7f825ef5599ec374f5387db58f82, which added a factory for `AdapterInterface`. Turns out the test expects all factories to be a `class-string`, but here a concrete instance is used. As far as I'm aware this is the only place in the many laminas packages we use where this is done.

Is there a reason for doing it this way, instead of having a `DefaultSerializerFactory` or similar? I thought one of the reasons for using strings in `ConfigProvider`s was to avoid loading unnecessary classes?

#### Current behavior

Factory is a concrete instance.

#### Expected behavior

Factory is a `class-string`.

**Comment by Xerkus** [comment]
Factory instance is not an issue really, but that factory is flawed and it IS a bug: the factory is not serializable for config cache using var_export. It is missing `__set_state()` https://www.php.net/manual/en/language.oop5.magic.php#object.set-state

This *will* lead to undefined method fatar error on trying to load config cache

**Comment by Xerkus** [comment]
I would prefer to go with alias and abstract factory used as concrete factory with service name as input since options are not needed in default config.

**Comment by boesing** [comment]
What version of `laminas-modulemanager` is used in your project?
I do use these kinds of factories with config cache enabled for years and it works flawless.

Modulemanager should be at least v2.10 and I guess `brick/varexporter` needs to be 0.3.8:
https://github.com/brick/varexporter/releases/tag/0.3.8

But not 100% sure about the latter. 🤔

**Comment by boesing** [comment]
> Turns out the test expects all factories to be a class-string, but here a concrete instance is used. As far as I'm aware this is the only place in the many laminas packages we use where this is done.

As per `laminas-servicemanager`, factories can be:

- `class-string<Factory\FactoryInterface>`
- instance of `Factory\FactoryInterface`
- `callable(ContainerInterface,?string,?array<mixed>|null):object` (objets just implementing `__invoke` with this signature are matching as well as these are treated as `callable` once initiated)

**Comment by Xerkus** [comment]
I see. I was not aware varexporter no longer uses var_export on objects.

**Comment by kynx** [comment]
@boesing These are Mezzio projects, so no `laminar-modulemanager`. 

Like I said, I’m not saying this is a bug. I questioned it because I haven’t seen it before and have always disallowed instances in our own configuration. If it’s acceptable to Laminas maybe I should loosen up 😀

**Comment by boesing** [comment]
frankly, I added this as I dislike these abstract factories which do not have proper psalm type inference.

Regarding "performance impact": 
every1 who takes time to actually benchmark this, can - in case of performance degradation - still overwrite the service configuration on project level.

I am still open to change this to `class-string` factory, pretty sure that this won't introduce any BC break when we switch the factory within the config to a different one.

Happy to get opinions here, I just added it as I do use this kind of factories all day long at work.

**Comment by Xerkus** [comment]
The way it involves (at least) two closure calls and reflection per object in config cache on top of using object over plain string, it could have a significant impact:
```php
'Laminas\\Serializer\\Adapter\\AdapterInterface' => (static function() {
    $class = new \ReflectionClass(\Laminas\Serializer\GenericSerializerFactory::class);
    $object = $class->newInstanceWithoutConstructor();

    (function() {
        $this->serializerName = 'Laminas\\Serializer\\Adapter\\PhpSerialize';
        $this->options = null;
    })->bindTo($object, \Laminas\Serializer\GenericSerializerFactory::class)();

    return $object;
})(),
```

By itself it won't be noticeable but should it be used as a general practice and with larger configurations it can have noticeable compounding effect.

I don't think any action is needed here.
