### ISSUE TITLE
Release 2.10 doesn't support PHP8

### ISSUE THREAD

**Issue by MatyCZ** [laminas/laminas-serializer#9]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0

#### Summary

Release notes for 2.10 mentioned support for PHP8, but composer.json file was not modified.

#### Current behavior

File `composer.json` still requires PHP `^5.6 || ^7.0`. 

#### How to reproduce

Try install this package with PHP8.

#### Expected behavior

Update `composer.json` file by changes mentioned in release notes.

**Comment by froschdesign** [comment]
@MatyCZ 
Thanks for reporting the problem! 👍 

Looks like something went wrong: the related pull request #7 was merged to `master` branch but there is no branch with this name.

**Comment by weierophinney** [comment]
Fixed with #10; 2.10.1 release coming shortly.
